 - name: Install influxdb Docker Container Svc
   template: src=../templates/influxdb.service.j2 dest=/etc/systemd/system/influxdb.service
   become: true
   notify: systemd daemon_reload

 - name: Create stats folder if it doesnt exist
   become: true
   file: path=/data/stats state=directory mode=0660

 - name: Create Stats Group
   become: true
   group: name=stats state=present

 - name: Create influxdb User
   become: true
   user: name=influxdb group=stats state=present system=yes createhome=no

 - name: Create influxdb Folder if it doesnt exist
   become: true
   file: path=/data/stats/influxdb state=directory mode=0660

 - name: Set influxdb Permissions
   become: true
   file:  path=/data/stats/influxdb owner=influxdb group=stats mode=0660 recurse=yes

 - name: Start influxdb
   become: true
   service: name=influxdb state=running enabled=true
