 - name: Install Couchpotato Docker Container Svc
   template: src=../templates/couchpotato.service.j2 dest=/etc/systemd/system/couchpotato.service
   become: true
   notify: systemd daemon_reload

 - name: Create UseNetConf Folder if it doesnt exist
   become: true
   file: path=/data/downloads/usenet/couchpotatoconf state=directory mode=0660

 - name: Set UseNetUsr Permissions
   become: true
   file:  path=/data/downloads/usenet/couchpotatoconf owner=usenetusr group=usenetgrp mode=0770 recurse=yes

 - name: Start couchpotato
   become: true
   service: name=couchpotato state=running enabled=true
