---

- name: Updating Package Lists.
  apt:
    update_cache: yes
#    cache_valid_time: 3600

- name: Upgrading Packages.
  apt:
    upgrade: dist

- name: Cleaning the Cache
  apt:
    autoclean: yes

- name: Removing old packages and purge the configs.
  become: yes
  apt:
    autoremove: yes
    purge: yes
