--- 
- 
  apt_key: "keyserver=hkp://p80.pool.sks-keyservers.net:80 id={{docker_repo_key_id}}"
  become: true
  name: "Install Docker Repo Key"
- 
  become: true
  name: "Install Docker source list"
  template: "src=../files/docker.list dest=/etc/apt/sources.list.d/docker.list"
- 
  apt: update_cache=yes
  become: true
  name: "Update Apt"
- 
  apt: "pkg={{item}} state=present"
  become: true
  name: "Install Docker dependancies"
  when: "ansible_distribution == \"Ubuntu\""
  with_items: 
    - apt-transport-https
    - ca-certificates
    - docker-engine
- 
  become: true
  group: "name=docker state=present"
  name: "Create Docker user group"
- 
  become: true
  name: "Add localuser to group"
  user: "name={{user}} groups=docker append=yes"

-
  become: true
  name: "Fix Docker IPTables - check docker.service.d exists"
  file: "path=/etc/systemd/system/docker.service.d state=directory recurse=yes"

-
  become: true
  name: "Fix Docker IPTables - copy config file"
  template: "src=..\files\noiptables.conf dest=/etc/systemd/system/docker.service.d/noiptables.conf"

-
  become: true
  name: "Start Docker"
  service: "name=docker state=started enabled=yes"
