---

 - name: Update the apt cache
   apt:
     update_cache: yes

 - name: Install Packages
   apt: name={{ item }} state=latest
   with_items: "{{ packages }}"
  
 - ufw:
     state: enabled

 - ufw:
     rule: allow
     name: OpenSSH

 - name: Install bash aliases
   template: src=../files/.bash_aliases dest=~/.bash_aliases

 - name: Set bash source
   raw: source ~/.bashrc

 - sysctl:
     name: vm.swappiness
     value: 5
     state: present
    
 - sysctl:
     name: net.ipv6.conf.all.disable_ipv6
     value: 1
     state: present
    
 - sysctl:
     name: net.ipv6.conf.default.disable_ipv6
     value: 1
     state: present
            
 - sysctl:
     name: net.ipv6.conf.lo.disable_ipv6
     value: 1
     state: present
     reload: yes

 - name: Install Glances
   become: true
   raw: "curl -L http://bit.ly/glances | /bin/bash"

 - name: Create UseNetGrp Group
   become: true
   group: name=usenetgrp state=present gid=1001

 - name: Create UseNetUsr User
   become: true
   user: name=usenetusr group=usenetgrp state=present system=yes home=no uid=999
