---

 - name: Update the apt cache
   apt:
     update_cache: yes

 - name: Install Packages
   apt: name={{ item }} state=latest
   with_items: "{{ packages }}"
  
 - ufw:
     state: enabled

 - ufw:
     rule: allow
     name: OpenSSH

 - name: Install bash aliases
   template: src=../files/.bash_aliases dest=~/.bash_aliases

 - name: Install bashrc
   template: src=../files/.bashrc dest=~/.bashrc

 - name: Set bash source
   raw: source ~/.bashrc

 - sysctl:
     name: vm.swappiness
     value: 5
     state: present
    
 - sysctl:
     name: net.ipv6.conf.all.disable_ipv6
     value: 1
     state: present
    
 - sysctl:
     name: net.ipv6.conf.default.disable_ipv6
     value: 1
     state: present
            
 - sysctl:
     name: net.ipv6.conf.lo.disable_ipv6
     value: 1
     state: present
     reload: yes

 - name: Install Glances
   become: true
   raw: "curl -L http://bit.ly/glances | /bin/bash"

 - name: Create UseNetGrp Group
   become: true
   group: name=usenetgrp state=present gid=1111

 - name: Create UseNetUsr User
   become: true
   user: name=usenetusr group=usenetgrp state=present system=yes createhome=no uid=999

 - name: Create Downloads Folder if it doesnt exist
   become: true
   file: path=/data/downloads state=directory mode=0770

 - name: Set UseNetUsr Permissions
   become: true
   file:  path=/data/downloads owner=usenetusr group=usenetgrp mode=0660 recurse=yes 

 - name: Ensure directories are 0770
   command: find /data/downloads -type d -exec chmod -c 0755 {} \;
   register: chmod_result
   changed_when: "chmod_result.stdout != \"\""
