---
- hosts: redis
  become: true
  vars:
     redis_url: 'http://download.redis.io/releases/redis-3.0.4.tar.gz'
     redis_dest: '/root/redis-3.0.4.tar.gz'
     redis_extracted_dest: '/root/redis-3.0.4'
     redis_config_location: '/etc/redis'
     packages: ['build-essential','nodejs','tcl']
     node_modules: ['pm2','redis-commander']

  tasks:
    - name: Add nodejs repo (1/2)
      apt_repository: repo="deb https://deb.nodesource.com/node_6.x jessie main" state=present

    - name: Add nodejs repo (2/2)
      apt_repository: repo="deb-src https://deb.nodesource.com/node_6.x jessie main" state=present

    - name: Add nodejs repo GPG key
      apt_key: url="https://deb.nodesource.com/gpgkey/nodesource.gpg.key" state=present

    - name: Install Make and Nodejs
      apt: name={{ item }} state=latest update_cache=yes
      with_items: "{{ packages }}"

    - name: Download redis
      get_url: url="{{ redis_url }}" dest="{{ redis_dest }}"

    - name: Create extract directory
      file: path="{{ redis_extracted_dest }}" state=directory mode=0755

    - name: Extract redis
      command: tar xvzf "{{ redis_dest }}"
      run_once: True

    - name: Make redis
      make: chdir="{{ redis_extracted_dest }}"
      run_once: True

    - name: Make Test redis
      make: chdir="{{ redis_extracted_dest }}" target="test"
      run_once: True

    - name: Make Install redis
      make: chdir="{{ redis_extracted_dest }}" target="install"
      run_once: True

    - name: Redis-Server systemd script
      action: copy src=redis-server.service
        dest=/etc/systemd/system/redis-server.service
        owner=0 group=0 mode=644

    - name: Create redis user
      user:  name=redis system=yes createhome=no

    - name: Create extract directory
      file: path=/etc/redis state=directory mode=0755

    - name: Setup Redis config
      template: src=redis.conf.j2 dest=/etc/redis/redis.conf

    - name: Start Redis-Server on boot
      service: name=redis-server enabled=yes state=started

    - name: Install NPM Modules
      command: npm install -g {{ item }}
      with_items: "{{ node_modules }}"

    - name: pm2 redis-commander
      command: pm2 start redis-commander

    - name: pm2 systemd script
      command: pm2 startup

    - name: Start pm2 on boot
      service: name=pm2 enabled=yes