---
- hosts: local
  vars:
    user: phasma
    
  
  roles:
#   - { role: standardbuild, tags: standardbuild }
#   - { role: fail2ban, tags: fail2ban}
#   - { role: sshd, tags: sshd}
#   - { role: caddy-ssl-proxy, tags: caddy-ssl-proxy}
#   - { role: docker, tags: docker}
#   - { role: docker-nzbget, tags: docker-nzbget}
    - { role: docker-sonarr, tags: docker-sonarr}
