 - name: Install NZBGet Docker Container Svc
   template: src=../templates/nzbget.service.j2 dest=/etc/systemd/system/nzbget.service
   become: true
   notify: systemd daemon_reload

 - name: Start NZBGet
   become: true
   service: name=nzbget state=running enabled=true
